// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoaAy4k03kC38D9HnwKq0XC-v_nczBrbU',
    appId: '1:312110533805:web:704a2ae66823f3c6bdca24',
    messagingSenderId: '312110533805',
    projectId: 'wifi-fcc1d',
    authDomain: 'wifi-fcc1d.firebaseapp.com',
    storageBucket: 'wifi-fcc1d.appspot.com',
    measurementId: 'G-15SX2WLLQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiHfjEgZyNiTVBmNEIKX2DjxhmsMkEE8',
    appId: '1:312110533805:android:0a67deed2ff68215bdca24',
    messagingSenderId: '312110533805',
    projectId: 'wifi-fcc1d',
    storageBucket: 'wifi-fcc1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpz8yBao9wnMAaxsWIMM_48Mlwg-IJJ8',
    appId: '1:312110533805:ios:e695998172ff4a61bdca24',
    messagingSenderId: '312110533805',
    projectId: 'wifi-fcc1d',
    storageBucket: 'wifi-fcc1d.appspot.com',
    iosBundleId: 'com.example.wifiCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOpz8yBao9wnMAaxsWIMM_48Mlwg-IJJ8',
    appId: '1:312110533805:ios:ccf60879335e89a8bdca24',
    messagingSenderId: '312110533805',
    projectId: 'wifi-fcc1d',
    storageBucket: 'wifi-fcc1d.appspot.com',
    iosBundleId: 'com.example.wifiCard.RunnerTests',
  );
}
